name: Coverage

on:
  workflow_run:
    workflows: [ Test ]
    branches: [ main ]
    types: 
      - completed

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Run Unit tests
        run: |
          npm install
          npm run test-coverage

      - name: Send coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: clover
