name: Dependabot auto-approve

on:
  workflow_run:
    workflows: [ Test ]
    types: 
      - completed

jobs:
  approve:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review --approve ${{ github.event.workflow_run.pull_requests[0].url }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
