name: Dependabot auto-approve

on: pull_request_target

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: gh pr comment ${{ github.event.pull_request.number }} --body "@dependabot merge"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
