name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Test, Dependabot ]
    types: 
      - completed

jobs:
  deploy:
    if: |
      github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: |
          echo ${{ toJSON(github) }}
          npm install
          npm run build

      - name: GitHub Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ${{ secrets.CNAME }}
